services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=server
      - SERVER_PORT=5678

  client_0: &client-template
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_0
    volumes:
      - ./input:/input:ro
      - ./output:/output
    depends_on:
      - server
    environment:
      - AGENCY_ID=0
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-0.csv
      - OUTPUT_FILE=/output/output-0.txt

  client_1:
    <<: *client-template
    container_name: client_1
    environment:
      - AGENCY_ID=1
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-1.csv
      - OUTPUT_FILE=/output/output-1.txt

  client_2:
    <<: *client-template
    container_name: client_2
    environment:
      - AGENCY_ID=2
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-2.csv
      - OUTPUT_FILE=/output/output-2.txt

  client_3:
    <<: *client-template
    container_name: client_3
    environment:
      - AGENCY_ID=3
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-3.csv
      - OUTPUT_FILE=/output/output-3.txt

  client_4:
    <<: *client-template
    container_name: client_4
    environment:
      - AGENCY_ID=4
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-4.csv
      - OUTPUT_FILE=/output/output-4.txt

  client_5:
    <<: *client-template
    container_name: client_5
    environment:
      - AGENCY_ID=5
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - INPUT_FILE=/input/input-5.csv
      - OUTPUT_FILE=/output/output-5.txt